[platformio]
default_envs = train

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

build_flags =
    -Wall
    -Wextra

[env:train]
build_flags =
    ${env.build_flags}
    -DDATASET_SEED=42UL

[env:validation]
build_flags =
    ${env.build_flags}
    -DDATASET_SEED=123UL

[env:test]
build_flags =
    ${env.build_flags}
    -DDATASET_SEED=999UL